const char HTML_BODY[] =
"<!DOCTYPE html>\n"
"<html lang='pt-br'>\n"
"<head>\n"
"  <meta charset='UTF-8'>\n"
"  <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
"  <title>Estação Meteorológica</title>\n"
"  <script src='https://cdn.jsdelivr.net/npm/chart.js'></script>\n"
"  <style>\n"
"    body { font-family: sans-serif; padding: 10px; background: #f0f0f0; margin: 0; }\n"
"    h1 { text-align: center; }\n"
"    .label { font-weight: bold; display: block; margin-top: 10px; }\n"
"    .input { padding: 5px; font-size: 16px; width: 80px; margin-top: 4px; }\n"
"    fieldset { border: 1px solid #ccc; padding: 10px; margin: 10px auto; width: 100%; max-width: 400px; }\n"
"    button { padding: 10px 16px; font-size: 16px; cursor: pointer; border-radius: 6px; border: none; background: #2196F3; color: white; margin-top: 10px; }\n"
"    .grid { display: flex; flex-wrap: wrap; justify-content: flex-start; gap: 20px; }\n"
"    .card { background: #fff; padding: 10px 20px; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.1); max-width: 1920px ; flex: 1; justify-content: flex-start; }\n"
"    .medicoes { display: flex; justify-content: space-around; gap: 10px; flex-wrap: wrap; margin-bottom: 20px; }\n"
"    .medicao { background: white; border-radius: 10px; padding: 10px; flex: 1; min-width: 120px; text-align: center; box-shadow: 0 0 6px rgba(0,0,0,0.1); }\n"
"    .temp { color: red; }\n"
"    .umid { color: blue; }\n"
"    .press { color: green; }\n"
"    canvas { width: 100% !important; height: auto !important; max-width: 1920px; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <h1>Estação Meteorológica</h1>\n"
"  <div class='medicoes'>\n"
"    <div class='medicao temp'>🌡️<br><strong>Temp:</strong> <span id='temp'>--</span> °C</div>\n"
"    <div class='medicao umid'>💧<br><strong>Umid:</strong> <span id='umid'>--</span> %</div>\n"
"    <div class='medicao press'>⏲️<br><strong>Pressão:</strong> <span id='pressao'>--</span> kPa</div>\n"
"    <div class='medicao'>⛰️<br><strong>Alt:</strong> <span id='alt'>--</span> m</div>\n"
"  </div>\n"
"  <div style='max-width: 95%; margin: 0 auto 20px;'>\n"
"    <canvas id='grafico'></canvas>\n"
"  </div>\n"
"  <div class='grid'>\n"
"    <form id='configForm' class='card'>\n"
"      <fieldset><legend>Temperatura (°C)</legend>\n"
"        <label class='label'>Mínima: <input class='input' type='number' name='temp_min'> <small>(Atual: <span id='tempMin'>--</span>)</small></label>\n"
"        <label class='label'>Máxima: <input class='input' type='number' name='temp_max'> <small>(Atual: <span id='tempMax'>--</span>)</small></label>\n"
"        <label class='label'>Offset: <input class='input' type='number' name='offset_temp'> <small>(Atual: <span id='offsetTemp'>--</span>)</small></label>\n"
"      </fieldset>\n"
"      <fieldset><legend>Umidade (%)</legend>\n"
"        <label class='label'>Mínima: <input class='input' type='number' name='umid_min'> <small>(Atual: <span id='umidMin'>--</span>)</small></label>\n"
"        <label class='label'>Máxima: <input class='input' type='number' name='umid_max'> <small>(Atual: <span id='umidMax'>--</span>)</small></label>\n"
"        <label class='label'>Offset: <input class='input' type='number' name='offset_umid'> <small>(Atual: <span id='offsetUmid'>--</span>)</small></label>\n"
"      </fieldset>\n"
"      <fieldset><legend>Pressão (kPa)</legend>\n"
"        <label class='label'>Mínima: <input class='input' type='number' name='press_min'> <small>(Atual: <span id='pressMin'>--</span>)</small></label>\n"
"        <label class='label'>Máxima: <input class='input' type='number' name='press_max'> <small>(Atual: <span id='pressMax'>--</span>)</small></label>\n"
"        <label class='label'>Offset: <input class='input' type='number' name='offset_press' step='0.1'> <small>(Atual: <span id='offsetPress'>--</span>)</small></label>\n"
"      </fieldset>\n"
"      <div style='display: flex; justify-content: center; align-items: center;'> <button type='submit'>Salvar Configurações</button> </div> \n"
"    </form>\n"
"  </div>\n"
"  <script>\n"
"    const ctx = document.getElementById('grafico').getContext('2d');\n"
"    const chart = new Chart(ctx, {\n"
"      type: 'line',\n"
"      data: { labels: [], datasets: [\n"
"        { label: 'Temperatura', data: [], borderColor: 'red', yAxisID: 'y1' },\n"
"        { label: 'Umidade', data: [], borderColor: 'blue', yAxisID: 'y2' },\n"
"        { label: 'Pressao', data: [], borderColor: 'green', yAxisID: 'y3' }\n"
"      ] },\n"
"      options: { responsive: true, animation: false }\n"
"    });\n"
"    function atualizar() {\n"
"      fetch('/estado')\n"
"        .then(resp => resp.json())\n"
"        .then(data => {\n"
"          document.getElementById('temp').textContent = data.temperatura.toFixed(2);\n"
"          document.getElementById('umid').textContent = data.umidade.toFixed(2);\n"
"          document.getElementById('pressao').textContent = data.pressao.toFixed(2);\n"
"          document.getElementById('alt').textContent = data.altitude.toFixed(2);\n"
"          document.getElementById('tempMin').textContent = data.temp_min.toFixed(2);\n"
"          document.getElementById('tempMax').textContent = data.temp_max.toFixed(2);\n"
"          document.getElementById('offsetTemp').textContent = data.offset_temp.toFixed(2);\n"
"          document.getElementById('umidMin').textContent = data.umid_min.toFixed(2);\n"
"          document.getElementById('umidMax').textContent = data.umid_max.toFixed(2);\n"
"          document.getElementById('offsetUmid').textContent = data.offset_umid.toFixed(2);\n"
"          document.getElementById('pressMin').textContent = data.press_min.toFixed(2);\n"
"          document.getElementById('pressMax').textContent = data.press_max.toFixed(2);\n"
"          document.getElementById('offsetPress').textContent = data.offset_press.toFixed(2);\n"
"          const hora = new Date().toLocaleTimeString();\n"
"          chart.data.labels.push(hora);\n"
"          chart.data.datasets[0].data.push(data.temperatura);\n"
"          chart.data.datasets[1].data.push(data.umidade);\n"
"          chart.data.datasets[2].data.push(data.pressao);\n"
"          if (chart.data.labels.length > 10) {\n"
"            chart.data.labels.shift();\n"
"            chart.data.datasets.forEach(ds => ds.data.shift());\n"
"          }\n"
"          chart.update();\n"
"        });\n"
"    }\n"
"    setInterval(atualizar, 2000);\n"
"    document.getElementById('configForm').addEventListener('submit', function(e) {\n"
"      e.preventDefault();\n"
"      const form = new FormData(this);\n"
"      const params = new URLSearchParams();\n"
"      for (const [k,v] of form.entries()) params.append(k, v);\n"
"      fetch('/config?' + params.toString())\n"
"        .then(resp => resp.ok ? alert('Configurações salvas!') : alert('Erro ao salvar.'));\n"
"    });\n"
"    atualizar();\n"
"  </script>\n"
"</body>\n"
"</html>\n";
